### ISSUE TITLE
Build Error Ubuntu 17.10

### ISSUE THREAD

**Issue by MasterCATZ** [MaartenBaert/ssr#590]
aio@aio:/mnt/Install/gitclone/ssr$ ./simple-build-and-install
Detecting architecture ...
Detecting ffmpeg/libav ...
  Detected ffmpeg.
Detecting Qt version ...
  Detected Qt4.
Auto-detected options:
  ENABLE_32BIT_GLINJECT = TRUE
  ENABLE_X86_ASM = TRUE
  ENABLE_FFMPEG_VERSIONS = TRUE
  WITH_QT5 = FALSE
  WITH_GLINJECT = TRUE
Entering build-release directory ...
Running cmake ...
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found ALSA: /usr/lib/x86_64-linux-gnu/libasound.so (found version "1.1.3") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for modules 'libavformat;libavcodec;libavutil;libswscale'
--   Found libavformat, version 58.0.102
--   Found libavcodec, version 58.2.100
--   Found libavutil, version 56.0.100
--   Found libswscale, version 5.0.101
-- Found AVFormat: /usr/local/lib/libavformat.a  
-- Found AVCodec: /usr/local/lib/libavcodec.a  
-- Found AVUtil: /usr/local/lib/libavutil.a  
-- Found SWScale: /usr/local/lib/libswscale.a  
-- Checking for module 'libpulse'
--   Found libpulse, version 10.0
-- Found PulseAudio: /usr/lib/x86_64-linux-gnu/libpulse.so  
-- Checking for module 'jack'
--   Found jack, version 1.9.11
-- Found Jack: /usr/lib/x86_64-linux-gnu/libjack.so  
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake-qt4 (found version "4.8.7") 
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/Install/gitclone/ssr/build-release
Compiling ...
Scanning dependencies of target translations
Scanning dependencies of target ssr-glinject32
Scanning dependencies of target ssr-glinject
[  1%] Generating qrc_resources.cxx
[  2%] Generating simplescreenrecorder_ar.qm
[  3%] Building C object glinject/CMakeFiles/ssr-glinject32.dir/elfhacks.c.o
[  4%] Building C object glinject/CMakeFiles/ssr-glinject.dir/elfhacks.c.o
[  4%] Generating AV/Input/moc_X11Input.cxx
[  5%] Generating simplescreenrecorder_bg.qm
[  6%] Generating AV/Output/moc_SyncDiagram.cxx
[  7%] Generating common/moc_Logger.cxx
[  8%] Generating simplescreenrecorder_cs.qm
[  9%] Generating GUI/moc_AudioPreviewer.cxx
[ 11%] Generating simplescreenrecorder_de.qm
[ 11%] Generating GUI/moc_DialogGLInject.cxx
[ 12%] Generating GUI/moc_ElidedLabel.cxx
[ 13%] Generating GUI/moc_HiddenScrollArea.cxx
[ 14%] Generating simplescreenrecorder_el.qm
[ 14%] Generating GUI/moc_HotkeyListener.cxx
[ 14%] Generating simplescreenrecorder_es.qm
[ 15%] Generating GUI/moc_MainWindow.cxx
[ 16%] Generating GUI/moc_PageDone.cxx
[ 17%] Generating simplescreenrecorder_fr.qm
[ 18%] Generating GUI/moc_PageInput.cxx
[ 19%] Generating GUI/moc_PageOutput.cxx
[ 20%] Generating simplescreenrecorder_he.qm
[ 21%] Generating GUI/moc_PageRecord.cxx
[ 22%] Generating GUI/moc_PageWelcome.cxx
[ 23%] Generating simplescreenrecorder_hu.qm
[ 24%] Generating GUI/moc_ProfileBox.cxx
[ 24%] Generating GUI/moc_VideoPreviewer.cxx
Scanning dependencies of target simplescreenrecorder
[ 25%] Generating simplescreenrecorder_id.qm
[ 26%] Building CXX object glinject/CMakeFiles/ssr-glinject.dir/GLInject.cpp.o
[ 27%] Generating simplescreenrecorder_it.qm
[ 28%] Generating simplescreenrecorder_ja.qm
[ 29%] Building CXX object glinject/CMakeFiles/ssr-glinject32.dir/GLInject.cpp.o
[ 30%] Generating simplescreenrecorder_lt.qm
[ 30%] Generating simplescreenrecorder_nl.qm
[ 31%] Generating simplescreenrecorder_pl.qm
[ 32%] Generating simplescreenrecorder_pt_BR.qm
[ 33%] Generating simplescreenrecorder_ru.qm
[ 34%] Generating simplescreenrecorder_sv.qm
[ 35%] Generating simplescreenrecorder_uk.qm
[ 36%] Generating simplescreenrecorder_zh_CN.qm
[ 37%] Generating simplescreenrecorder_zh_TW.qm
[ 37%] Built target translations
[ 38%] Building CXX object glinject/CMakeFiles/ssr-glinject32.dir/GLXFrameGrabber.cpp.o
[ 38%] Building CXX object glinject/CMakeFiles/ssr-glinject.dir/GLXFrameGrabber.cpp.o
[ 39%] Building CXX object glinject/CMakeFiles/ssr-glinject32.dir/Hook.cpp.o
[ 39%] Building CXX object glinject/CMakeFiles/ssr-glinject32.dir/SSRVideoStreamWriter.cpp.o
[ 40%] Building CXX object src/CMakeFiles/simplescreenrecorder.dir/AV/Input/ALSAInput.cpp.o
[ 41%] Building CXX object glinject/CMakeFiles/ssr-glinject.dir/Hook.cpp.o
[ 42%] Building CXX object glinject/CMakeFiles/ssr-glinject.dir/SSRVideoStreamWriter.cpp.o
[ 43%] Linking CXX shared library lib32/libssr-glinject.so
/usr/bin/ld: skipping incompatible //usr/lib/x86_64-linux-gnu/libX11.so when searching for -lX11
/usr/bin/ld: skipping incompatible //usr/lib/x86_64-linux-gnu/libX11.a when searching for -lX11
/usr/bin/ld: cannot find -lX11
/usr/bin/ld: skipping incompatible //usr/lib/x86_64-linux-gnu/libXfixes.so when searching for -lXfixes
/usr/bin/ld: skipping incompatible //usr/lib/x86_64-linux-gnu/libXfixes.a when searching for -lXfixes
/usr/bin/ld: cannot find -lXfixes
/usr/bin/ld: skipping incompatible //usr/lib/x86_64-linux-gnu/libGLU.so when searching for -lGLU
/usr/bin/ld: skipping incompatible //usr/lib/x86_64-linux-gnu/libGLU.a when searching for -lGLU
/usr/bin/ld: cannot find -lGLU
/usr/bin/ld: skipping incompatible //usr/lib/x86_64-linux-gnu/libGL.so when searching for -lGL
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
glinject/CMakeFiles/ssr-glinject32.dir/build.make:202: recipe for target 'glinject/lib32/libssr-glinject.so' failed
make[2]: *** [glinject/lib32/libssr-glinject.so] Error 1
CMakeFiles/Makefile2:124: recipe for target 'glinject/CMakeFiles/ssr-glinject32.dir/all' failed
make[1]: *** [glinject/CMakeFiles/ssr-glinject32.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 44%] Building CXX object src/CMakeFiles/simplescreenrecorder.dir/AV/Input/GLInjectInput.cpp.o
[ 45%] Building CXX object src/CMakeFiles/simplescreenrecorder.dir/AV/Input/JACKInput.cpp.o
[ 46%] Linking CXX shared library libssr-glinject.so
[ 46%] Built target ssr-glinject
[ 47%] Building CXX object src/CMakeFiles/simplescreenrecorder.dir/AV/Input/PulseAudioInput.cpp.o
[ 48%] Building CXX object src/CMakeFiles/simplescreenrecorder.dir/AV/Input/SSRVideoStreamReader.cpp.o
[ 49%] Building CXX object src/CMakeFiles/simplescreenrecorder.dir/AV/Input/SSRVideoStreamWatcher.cpp.o
[ 49%] Building CXX object src/CMakeFiles/simplescreenrecorder.dir/AV/Input/X11Input.cpp.o
[ 50%] Building CXX object src/CMakeFiles/simplescreenrecorder.dir/AV/Output/AudioEncoder.cpp.o
[ 51%] Building CXX object src/CMakeFiles/simplescreenrecorder.dir/AV/Output/BaseEncoder.cpp.o
/mnt/Install/gitclone/ssr/src/AV/Output/AudioEncoder.cpp: In member function ‘unsigned int AudioEncoder::GetFrameSize()’:
/mnt/Install/gitclone/ssr/src/AV/Output/AudioEncoder.cpp:62:51: error: ‘CODEC_CAP_VARIABLE_FRAME_SIZE’ was not declared in this scope
  return (GetCodecContext()->codec->capabilities & CODEC_CAP_VARIABLE_FRAME_SIZE)? DEFAULT_FRAME_SAMPLES : GetCodecContext()->frame_size;
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/Install/gitclone/ssr/src/AV/Output/AudioEncoder.cpp:62:51: note: suggested alternative: ‘AV_CODEC_CAP_VARIABLE_FRAME_SIZE’
  return (GetCodecContext()->codec->capabilities & CODEC_CAP_VARIABLE_FRAME_SIZE)? DEFAULT_FRAME_SAMPLES : GetCodecContext()->frame_size;
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                   AV_CODEC_CAP_VARIABLE_FRAME_SIZE
/mnt/Install/gitclone/ssr/src/AV/Output/AudioEncoder.cpp: In static member function ‘static void AudioEncoder::PrepareStream(AVStream*, AVCodecContext*, AVCodec*, AVDictionary**, const std::vector<std::pair<QString, QString> >&, unsigned int, unsigned int, unsigned int)’:
/mnt/Install/gitclone/ssr/src/AV/Output/AudioEncoder.cpp:126:28: error: ‘CODEC_FLAG_QSCALE’ was not declared in this scope
    codec_context->flags |= CODEC_FLAG_QSCALE;
                            ^~~~~~~~~~~~~~~~~
/mnt/Install/gitclone/ssr/src/AV/Output/AudioEncoder.cpp:126:28: note: suggested alternative: ‘AV_CODEC_FLAG_QSCALE’
    codec_context->flags |= CODEC_FLAG_QSCALE;
                            ^~~~~~~~~~~~~~~~~
                            AV_CODEC_FLAG_QSCALE
[ 52%] Building CXX object src/CMakeFiles/simplescreenrecorder.dir/AV/Output/Muxer.cpp.o
src/CMakeFiles/simplescreenrecorder.dir/build.make:317: recipe for target 'src/CMakeFiles/simplescreenrecorder.dir/AV/Output/AudioEncoder.cpp.o' failed
make[2]: *** [src/CMakeFiles/simplescreenrecorder.dir/AV/Output/AudioEncoder.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/mnt/Install/gitclone/ssr/src/AV/Output/BaseEncoder.cpp: In member function ‘void BaseEncoder::EncoderThread()’:
/mnt/Install/gitclone/ssr/src/AV/Output/BaseEncoder.cpp:217:64: error: ‘CODEC_CAP_DELAY’ was not declared in this scope
   if(!m_should_stop && (m_codec_context->codec->capabilities & CODEC_CAP_DELAY)) {
                                                                ^~~~~~~~~~~~~~~
/mnt/Install/gitclone/ssr/src/AV/Output/BaseEncoder.cpp:217:64: note: suggested alternative: ‘AV_CODEC_CAP_DELAY’
   if(!m_should_stop && (m_codec_context->codec->capabilities & CODEC_CAP_DELAY)) {
                                                                ^~~~~~~~~~~~~~~
                                                                AV_CODEC_CAP_DELAY
src/CMakeFiles/simplescreenrecorder.dir/build.make:341: recipe for target 'src/CMakeFiles/simplescreenrecorder.dir/AV/Output/BaseEncoder.cpp.o' failed
make[2]: *** [src/CMakeFiles/simplescreenrecorder.dir/AV/Output/BaseEncoder.cpp.o] Error 1
/mnt/Install/gitclone/ssr/src/AV/Output/Muxer.cpp: In member function ‘AVStream* Muxer::AddStream(AVCodec*, AVCodecContext**)’:
/mnt/Install/gitclone/ssr/src/AV/Output/Muxer.cpp:317:30: error: ‘CODEC_FLAG_GLOBAL_HEADER’ was not declared in this scope
   (*codec_context)->flags |= CODEC_FLAG_GLOBAL_HEADER;
                              ^~~~~~~~~~~~~~~~~~~~~~~~
/mnt/Install/gitclone/ssr/src/AV/Output/Muxer.cpp:317:30: note: suggested alternative: ‘AV_CODEC_FLAG_GLOBAL_HEADER’
   (*codec_context)->flags |= CODEC_FLAG_GLOBAL_HEADER;
                              ^~~~~~~~~~~~~~~~~~~~~~~~
                              AV_CODEC_FLAG_GLOBAL_HEADER
/mnt/Install/gitclone/ssr/src/AV/Output/Muxer.cpp:320:27: error: ‘CODEC_CAP_EXPERIMENTAL’ was not declared in this scope
  if(codec->capabilities & CODEC_CAP_EXPERIMENTAL) {
                           ^~~~~~~~~~~~~~~~~~~~~~
/mnt/Install/gitclone/ssr/src/AV/Output/Muxer.cpp:320:27: note: suggested alternative: ‘AV_CODEC_CAP_EXPERIMENTAL’
  if(codec->capabilities & CODEC_CAP_EXPERIMENTAL) {
                           ^~~~~~~~~~~~~~~~~~~~~~
                           AV_CODEC_CAP_EXPERIMENTAL
src/CMakeFiles/simplescreenrecorder.dir/build.make:365: recipe for target 'src/CMakeFiles/simplescreenrecorder.dir/AV/Output/Muxer.cpp.o' failed
make[2]: *** [src/CMakeFiles/simplescreenrecorder.dir/AV/Output/Muxer.cpp.o] Error 1
CMakeFiles/Makefile2:179: recipe for target 'src/CMakeFiles/simplescreenrecorder.dir/all' failed
make[1]: *** [src/CMakeFiles/simplescreenrecorder.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
aio@aio:/mnt/Install/gitclone/ssr$

**Comment by h1z1** [comment]
> [ 43%] Linking CXX shared library lib32/libssr-glinject.so
> /usr/bin/ld: skipping incompatible //usr/lib/x86_64-linux-gnu/libX11.so when searching for -lX11


Ran into similar problems with the 32bit build.  cmake isn't pulling the right dependencies.  Still ran into the second part of that re libav.

**Comment by juozaspo** [comment]
You might need gcc-multilib and g++-multilib if to make it work; Had encountered similar bug earlier; Also make sure 32 bit versions of your development libraries are installed
To install 32 bit versions of incompatible 64 bit counterparts make sure 32 bit architecture is enabled in dpkg. The commands below fix most of "skipping incompatible *.so" errors after you install them.
```
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install libx11-dev:i386 libxfixes-dev:i386 libglu1-mesa-dev:i386 libgl1-mesa-dev:i386
```

**Comment by MaartenBaert** [comment]
That only works on newer versions of Ubuntu, before 16.04 it was unfortunately not possible to install the 32-bit and 64-bit version of libGL/libGLU at the same time. The instructions in the README were really old, I've updated the README now.

**Comment by syslogic** [comment]
on CentOS I've had the same 32bit dependency issues (the error message brought me here) ...

the equivalent command to install them is:

    sudo yum install glibc-devel.i686 libX11-devel.i686 libXfixes-devel.i686 mesa-libGLU-devel.i686 mesa-libGL-devel.i686

**Comment by h1z1** [comment]
Indeed.  cmake should be updated to reflect the right architecture version though based on the build.

**Comment by spacimek** [comment]
Note that for Centos8 you might have some dependency fights for glibc. 

I had to install it as:
sudo dnf install glibc-devel.i686 --disablerepo=AppStream,Stream-AppStream,Stream-BaseOS

And then I could:
sudo dnf install libX11-devel.i686 libXfixes-devel.i686 mesa-libGLU-devel.i686 mesa-libGL-devel.i686

In case you still have issues, you might need to: sudo dnf remove glibc32.x86_64 - and try again
